### ISSUE TITLE
Fails to build with Wayfire 0.8.0 (2021-11-26 snapshot)

### ISSUE THREAD

**Issue by CrezyDud** [WayfireWM/wayfire-plugins-extra#109]
```
ninja: Entering directory `build'
[28/41] Compiling C++ object src/libhinge.so.p/hinge.cpp.o
../src/hinge.cpp: In static member function ‘static void wayfire_hinge::send_message(wayfire_hinge::thread_message, int)’:
../src/hinge.cpp:107:14: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  107 |         write(write_fd, &message, 1);
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~
../src/hinge.cpp: In static member function ‘static int wayfire_hinge::on_pipe_update(int, uint32_t, void*)’:
../src/hinge.cpp:114:13: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  114 |         read(that->pipefd[0], &message, 1);
      |         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[32/41] Compiling C++ object src/libfollow-focus.so.p/follow-focus.cpp.o
FAILED: src/libfollow-focus.so.p/follow-focus.cpp.o
ccache c++ -Isrc/libfollow-focus.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fPIC -pthread -MD -MQ src/libfollow-focus.so.p/follow-focus.cpp.o -MF src/libfollow-focus.so.p/follow-focus.cpp.o.d -o src/libfollow-focus.so.p/follow-focus.cpp.o -c ../src/follow-focus.cpp
../src/follow-focus.cpp: In member function ‘virtual void follow_focus::wayfire_follow_focus::init()’:
../src/follow-focus.cpp:175:57: error: cannot convert ‘wf::signal_callback_t*’ {aka ‘std::function<void(wf::signal_data_t*)>*’} to ‘wf::signal_connection_t*’
  175 |         wf::get_core().connect_signal("pointer_motion", &pointer_motion);
      |                                                         ^~~~~~~~~~~~~~~
      |                                                         |
      |                                                         wf::signal_callback_t* {aka std::function<void(wf::signal_data_t*)>*}
In file included from /usr/include/wayfire/core.hpp:4,
                 from ../src/follow-focus.cpp:24:
/usr/include/wayfire/object.hpp:76:64: note:   initializing argument 2 of ‘void wf::signal_provider_t::connect_signal(std::string, wf::signal_connection_t*)’
   76 |     void connect_signal(std::string name, signal_connection_t *callback);
      |                                           ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../src/follow-focus.cpp: In member function ‘virtual void follow_focus::wayfire_follow_focus::fini()’:
../src/follow-focus.cpp:180:41: error: no matching function for call to ‘wf::compositor_core_t::disconnect_signal(const char [15], wf::signal_callback_t*)’
  180 |         wf::get_core().disconnect_signal("pointer_motion", &pointer_motion);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/wayfire/core.hpp:4,
                 from ../src/follow-focus.cpp:24:
/usr/include/wayfire/object.hpp:78:10: note: candidate: ‘void wf::signal_provider_t::disconnect_signal(wf::signal_connection_t*)’
   78 |     void disconnect_signal(signal_connection_t *callback);
      |          ^~~~~~~~~~~~~~~~~
/usr/include/wayfire/object.hpp:78:10: note:   candidate expects 1 argument, 2 provided
[36/41] Compiling C++ object src/libforce-fullscreen.so.p/force-fullscreen.cpp.o
FAILED: src/libforce-fullscreen.so.p/force-fullscreen.cpp.o
ccache c++ -Isrc/libforce-fullscreen.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fPIC -pthread -MD -MQ src/libforce-fullscreen.so.p/force-fullscreen.cpp.o -MF src/libforce-fullscreen.so.p/force-fullscreen.cpp.o.d -o src/libforce-fullscreen.so.p/force-fullscreen.cpp.o -c ../src/force-fullscreen.cpp
../src/force-fullscreen.cpp: In member function ‘void wayfire_force_fullscreen::connect_motion_signal()’:
../src/force-fullscreen.cpp:483:57: error: cannot convert ‘wf::signal_callback_t*’ {aka ‘std::function<void(wf::signal_data_t*)>*’} to ‘wf::signal_connection_t*’
  483 |         wf::get_core().connect_signal("pointer_motion", &on_motion_event);
      |                                                         ^~~~~~~~~~~~~~~~
      |                                                         |
      |                                                         wf::signal_callback_t* {aka std::function<void(wf::signal_data_t*)>*}
In file included from /usr/include/wayfire/core.hpp:4,
                 from ../src/force-fullscreen.cpp:27:
/usr/include/wayfire/object.hpp:76:64: note:   initializing argument 2 of ‘void wf::signal_provider_t::connect_signal(std::string, wf::signal_connection_t*)’
   76 |     void connect_signal(std::string name, signal_connection_t *callback);
      |                                           ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../src/force-fullscreen.cpp: In member function ‘void wayfire_force_fullscreen::disconnect_motion_signal()’:
../src/force-fullscreen.cpp:494:41: error: no matching function for call to ‘wf::compositor_core_t::disconnect_signal(const char [15], wf::signal_callback_t*)’
  494 |         wf::get_core().disconnect_signal("pointer_motion", &on_motion_event);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/wayfire/core.hpp:4,
                 from ../src/force-fullscreen.cpp:27:
/usr/include/wayfire/object.hpp:78:10: note: candidate: ‘void wf::signal_provider_t::disconnect_signal(wf::signal_connection_t*)’
   78 |     void disconnect_signal(signal_connection_t *callback);
      |          ^~~~~~~~~~~~~~~~~
/usr/include/wayfire/object.hpp:78:10: note:   candidate expects 1 argument, 2 provided
[38/41] Compiling C++ object src/libautorotate-iio.so.p/autorotate-iio.cpp.o
FAILED: src/libautorotate-iio.so.p/autorotate-iio.cpp.o
ccache c++ -Isrc/libautorotate-iio.so.p -Isrc -I../src -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -I/usr/include/giomm-2.4 -I/usr/lib/giomm-2.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fPIC -pthread -MD -MQ src/libautorotate-iio.so.p/autorotate-iio.cpp.o -MF src/libautorotate-iio.so.p/autorotate-iio.cpp.o.d -o src/libautorotate-iio.so.p/autorotate-iio.cpp.o -c ../src/autorotate-iio.cpp
../src/autorotate-iio.cpp: In member function ‘virtual void WayfireAutorotateIIO::init( ’:
../src/autorotate-iio.cpp:167:13: error: cannot convert ‘wf::signal_callback_t*’ {aka ‘std::function<void(wf::signal_data_t*)>*’} to ‘wf::signal_connection_t*’
  167 |             &on_input_devices_changed);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             |
      |             wf::signal_callback_t* {aka std::function<void(wf::signal_data_t*)>*}
In file included from /usr/include/wayfire/output.hpp:5,
                 from ../src/autorotate-iio.cpp:2:
/usr/include/wayfire/object.hpp:76:64: note:   initializing argument 2 of ‘void wf::signal_provider_t::connect_signal(std::string, wf::signal_connection_t*)’
   76 |     void connect_signal(std::string name, signal_connection_t *callback);
      |                                           ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../src/autorotate-iio.cpp: In member function ‘virtual void WayfireAutorotateIIO::fini( ’:
../src/autorotate-iio.cpp:257:41: error: no matching function for call to ‘wf::compositor_core_t::disconnect_signal(const char [19], wf::signal_callback_t*)’
  257 |         wf::get_core().disconnect_signal("input-device-added",
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
  258 |             &on_input_devices_changed);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/wayfire/output.hpp:5,
                 from ../src/autorotate-iio.cpp:2:
/usr/include/wayfire/object.hpp:78:10: note: candidate: ‘void wf::signal_provider_t::disconnect_signal(wf::signal_connection_t*)’
   78 |     void disconnect_signal(signal_connection_t *callback);
      |          ^~~~~~~~~~~~~~~~~
/usr/include/wayfire/object.hpp:78:10: note:   candidate expects 1 argument, 2 provided
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'wayfire-plugins-extra-git-r71.a3412ee-1':
error: packages failed to build: wayfire-plugins-extra-git-r71.a3412ee-1
```

**Comment by jbeich** [comment]
Can you change issue title to "Fails to build with Wayfire 0.8.0 (2021-11-26 snapshot)" ?

Regressed by https://github.com/WayfireWM/wayfire/commit/9f2a7679f5bb. Clang error:
```c++
src/follow-focus.cpp:175:57: error: cannot initialize a parameter of type 'wf::signal_connection_t *' with an rvalue of type 'wf::signal_callback_t *' (aka 'function<void (wf::signal_data_t *)> *')
        wf::get_core().connect_signal("pointer_motion", &pointer_motion);
                                                        ^~~~~~~~~~~~~~~
/usr/include/wayfire/object.hpp:76:64: note: passing argument to parameter 'callback' here
    void connect_signal(std::string name, signal_connection_t *callback);
                                                               ^
src/follow-focus.cpp:180:60: error: too many arguments to function call, expected single argument 'callback', have 2 arguments
        wf::get_core().disconnect_signal("pointer_motion", &pointer_motion);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ^~~~~~~~~~~~~~~
/usr/include/wayfire/object.hpp:78:10: note: 'disconnect_signal' declared here
    void disconnect_signal(signal_connection_t *callback);
         ^
src/autorotate-iio.cpp:167:13: error: cannot initialize a parameter of type 'wf::signal_connection_t *' with an rvalue of type 'wf::signal_callback_t *' (aka 'function<void (wf::signal_data_t *)> *')
            &on_input_devices_changed);
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wayfire/object.hpp:76:64: note: passing argument to parameter 'callback' here
    void connect_signal(std::string name, signal_connection_t *callback);
                                                               ^
src/autorotate-iio.cpp:258:13: error: too many arguments to function call, expected single argument 'callback', have 2 arguments
            &on_input_devices_changed);
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wayfire/object.hpp:78:10: note: 'disconnect_signal' declared here
    void disconnect_signal(signal_connection_t *callback);
         ^
src/force-fullscreen.cpp:483:57: error: cannot initialize a parameter of type 'wf::signal_connection_t *' with an rvalue of type 'wf::signal_callback_t *' (aka 'function<void (wf::signal_data_t *)> *')
        wf::get_core().connect_signal("pointer_motion", &on_motion_event);
                                                        ^~~~~~~~~~~~~~~~
/usr/include/wayfire/object.hpp:76:64: note: passing argument to parameter 'callback' here
    void connect_signal(std::string name, signal_connection_t *callback);
                                                               ^
src/force-fullscreen.cpp:494:60: error: too many arguments to function call, expected single argument 'callback', have 2 arguments
        wf::get_core().disconnect_signal("pointer_motion", &on_motion_event);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ^~~~~~~~~~~~~~~~
/usr/include/wayfire/object.hpp:78:10: note: 'disconnect_signal' declared here
    void disconnect_signal(signal_connection_t *callback);
         ^
```

**Comment by CrezyDud** [comment]
alright
