### ISSUE TITLE
Release 0.7.0 fails to build with wayfire 0.7.3

### ISSUE THREAD

**Issue by magthe** [WayfireWM/wayfire-plugins-extra#126]
Failing on Arch with:

```
[27/37] Compiling C++ object src/libmag.so.p/mag.cpp.o
FAILED: src/libmag.so.p/mag.cpp.o
c++ -Isrc/libmag.so.p -Isrc -I../wayfire-plugins-extra-0.7.0/src -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O0 -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -Wno-unused-parameter -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fPIC -pthread -MD -MQ src/libmag.so.p/mag.cpp.o -MF src/libmag.so.p/mag.cpp.o.d -o src/libmag.so.p/mag.cpp.o -c ../wayfire-plugins-extra-0.7.0/src/mag.cpp
../wayfire-plugins-extra-0.7.0/src/mag.cpp: In lambda function:
../wayfire-plugins-extra-0.7.0/src/mag.cpp:178:14: error: ‘wlr_output_export_dmabuf’ was not declared in this scope; did you mean ‘wlr_output_event_damage’?
  178 |         if (!wlr_output_export_dmabuf(output->handle, &dmabuf_attribs))
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
      |              wlr_output_event_damage
[32/37] Compiling C++ object src/libworkspace-names.so.p/workspace-names.cpp.o
```

**Comment by magthe** [comment]
All the other plugins seem to build fine though.

**Comment by marcusbritanicus** [comment]
@magthe i think git should compile.

**Comment by magthe** [comment]
Nice, then I have something to try out.

**Comment by marcusbritanicus** [comment]
@magthe I believe I was wrong. git probably will not compile with 0.7.3
However, the good news is you can simply copy mag.cpp from git into 0.7.x and you'll be able to compile. If you succeed, please let me know. I will open a MR with the change.

**Comment by magthe** [comment]
@marcusbritanicus that builds beautifully!

**Comment by marcusbritanicus** [comment]
@magthe Could you also please test the magnifier plugin for me?

**Comment by koyo-nic** [comment]
> @magthe Could you also please test the magnifier plugin for me?

Hi. ~Unrelated~ I have arrived here after trying to upgrade from `v0.7.0-1 to v0.7.0-2` available in AUR/paru. I was getting similar error message. As far as the issue is concerned I have  tested the magnifier and it works.
I am using garuda linux.
![meson build](https://user-images.githubusercontent.com/50481279/170205130-1eff4fcc-8892-4452-b183-5f4c79f448dc.jpeg)
![ninja build](https://user-images.githubusercontent.com/50481279/170205281-b2bbbd3a-24ad-4835-bc5e-a9b
![test](https://user-images.githubusercontent.com/50481279/170205684-5239da1e-82d3-4831-bab3-7812064b434e.jpeg)
1af6e40b9.jpeg)

**Comment by marcusbritanicus** [comment]
@koyo-nic What is your wayfire version? If your wayfire version is v0.7.3, then v0.7.0-2 will not compile. You'll have to either use Wayfire v0.7.2 or wait for w-p-e release or compile from git, pulling in #127

**Comment by koyo-nic** [comment]
@marcusbritanicus That's alright. Thanks for the directions. Using Wayfire version v0.7.3

**Comment by dr460nf1r3** [comment]
Fixed the AUR PKGBUILD in https://github.com/chaotic-aur/interfere/commit/db6d0f6df343e9ed1b48e438b97e4331818c72d8. Now the maintainer just needs to patch that PKGBUILD :) thanks @marcusbritanicus for fixing it!

**Comment by soreau** [comment]
This seems to be fixed, closing.
